/*
 * @Author: jdm
 * @Date: 2024-08-07 11:04:18
 * @LastEditors: jdm
 * @LastEditTime: 2024-09-03 16:44:41
 * @FilePath: \vite-vue3-jdm\typings\components.d.ts
 * @Description:
 *
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { };

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: (typeof import('./../src/components/common/AppCard.vue'))['default'];
    Application: (typeof import('./../src/components/application/Application.vue'))['default'];
    AppPage: (typeof import('./../src/components/common/AppPage.vue'))['default'];
    BasicForm: (typeof import('./../src/components/Form/src/BasicForm.vue'))['default'];
    CommonWrapper: (typeof import('./../src/components/common/CommonWrapper.vue'))['default'];
    HelloWorld: (typeof import('./../src/components/HelloWorld.vue'))['default'];
    JayIcon: (typeof import('./../src/components/common/JayIcon.vue'))['default'];
    NA: (typeof import('naive-ui'))['NA'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCheckbox: (typeof import('naive-ui'))['NCheckbox'];
    NColorPicker: (typeof import('naive-ui'))['NColorPicker'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDataTable: (typeof import('naive-ui'))['NDataTable'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NDivider: (typeof import('naive-ui'))['NDivider'];
    NDrawer: (typeof import('naive-ui'))['NDrawer'];
    NDrawerContent: (typeof import('naive-ui'))['NDrawerContent'];
    NDropdown: (typeof import('naive-ui'))['NDropdown'];
    NEl: (typeof import('naive-ui'))['NEl'];
    NFlex: (typeof import('naive-ui'))['NFlex'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NFormItem: (typeof import('naive-ui'))['NFormItem'];
    NIcon: (typeof import('naive-ui'))['NIcon'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NInputNumber: (typeof import('naive-ui'))['NInputNumber'];
    NLayout: (typeof import('naive-ui'))['NLayout'];
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent'];
    NLayoutFooter: (typeof import('naive-ui'))['NLayoutFooter'];
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader'];
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMenu: (typeof import('naive-ui'))['NMenu'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NP: (typeof import('naive-ui'))['NP'];
    NPopselect: (typeof import('naive-ui'))['NPopselect'];
    NScrollbar: (typeof import('naive-ui'))['NScrollbar'];
    NSelect: (typeof import('naive-ui'))['NSelect'];
    NSpace: (typeof import('naive-ui'))['NSpace'];
    NSwitch: (typeof import('naive-ui'))['NSwitch'];
    NTab: (typeof import('naive-ui'))['NTab'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NText: (typeof import('naive-ui'))['NText'];
    NTooltip: (typeof import('naive-ui'))['NTooltip'];
    NWatermark: (typeof import('naive-ui'))['NWatermark'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    Table: (typeof import('./../src/components/jayTable/src/Table.vue'))['default'];
    TheLogo: (typeof import('./../src/components/common/TheLogo.vue'))['default'];
    Toolbar: (typeof import('../src/components/jayTable/src/components/Toolbar.vue'))['default'];
    Watermark: (typeof import('./../src/components/common/Watermark.vue'))['default'];
  }
}
